Repository frenck/python-tailscale, pull requests merged in 2023-11, with the labels that each got.

#438 Fix spelling error (causing CI failure)
  .github/labels.yml
Labels: maintenance

#439 Update development toolchain
  .deepsource.toml
  .devcontainer/devcontainer.json
  .flake8
  .github/workflows/codeql.yaml
  .github/workflows/linting.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .github/workflows/typing.yaml
  .nvmrc
  .pre-commit-config.yaml
  LICENSE.md
  README.md
  examples/devices.py
  examples/ruff.toml
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  sonar-project.properties
  src/tailscale/models.py
  src/tailscale/tailscale.py
  tests/__init__.py
  tests/ruff.toml
  tests/test_tailscale.py
Labels: breaking-change, maintenance

#428 Remove derp section from ClientConnectivity model
  src/tailscale/models.py
Labels: bugfix

#440 Add forward compatibility for Pydantic v2
  src/tailscale/models.py
Labels: bugfix

#441 Replace async_timeout with asyncio.timeout
  src/tailscale/tailscale.py
Labels: enhancement

#442 Revert pydantic v2 support
  poetry.lock
  pyproject.toml
  src/tailscale/models.py
Labels: bugfix

#443 Replace pydantic with mashumaro
  poetry.lock
  pyproject.toml
  src/tailscale/models.py
  src/tailscale/tailscale.py
  tests/test_tailscale.py
Labels: enhancement

#444 Replace dependabot with renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: maintenance
